format = """
[░▒▓](#85a8d2)\
[](#85a8d2)\
$os\
$username\
[](bg:#739bcb fg:#85a8d2)\
$directory\
[](fg:#739bcb bg:#608EC4)\
$git_branch\
$git_status\
[](bg:#608EC4 fg:#608EC4)\
[ ](fg:#608EC4)\
"""

[username]
show_always = true
style_user = "bg:#85a8d2 fg:#DFA7BF"
style_root = "bg:#85a8d2"
format = '[  $user ]($style)'
 
[directory]
style = "bg:#739bcb fg:#DFA7BF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[➜](bold purple)"
error_symbol = "[✗](bold red)"

[git_branch]
symbol = ""
style = "bg:#608ec4 fg:#DFA7BF"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#DFA7BF fg: #DFA7BF"
format = '[$all_status$ahead_behind ]($style)'
