format = """
[░▒▓](#edccda)\
[](#edccda)\
$os\
$username\
[](bg:#e6bacd fg:#edccda)\
$directory\
[](fg:#e6bacd bg:#DFA7BF)\
$git_branch\
$git_status\
[](bg:#DFA7BF fg:#DFA7BF)\
[ ](fg:#DFA7BF)\
"""

[username]
show_always = true
style_user = "bg:#edccda fg:#608EC4"
style_root = "bg:#edccda"
format = '[  $user ]($style)'
 
[directory]
style = "bg:#e6bacd fg:#608EC4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[➜](bold purple)"
error_symbol = "[✗](bold red)"

[git_branch]
symbol = ""
style = "bg:#DFA7BF fg:#608EC4"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#DFA7BF fg: #608EC4"
format = '[$all_status$ahead_behind ]($style)'
