format = """
[](#6f00ff)\
$os\
$username\
[](bg:#6a5acd fg:#6f00ff)\
$directory\
[](fg:#6a5acd bg:#58427c)\
$git_branch\
$git_status\
[](bg:#58427c fg:#58427c)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$python\
$rust\
[ ](bg:#967bb6 fg:#58427c)\
$time\
[ ](fg:#967bb6)\
"""

[username]
show_always = true
style_user = "bg:#6f00ff"
style_root = "bg:#6f00ff"
format = '[$user ]($style)'
 
[directory]
style = "bg:#6a5acd"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[➜](bold purple)"
error_symbol = "[✗](bold red)"

[python]
#symbol = ""
style = "bg:#58427c"
format = '[ $symbol $version]($style)'

[git_branch]
symbol = ""
style = "bg:#58427c"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#58427c"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#967bb6"
format = '[ $time ]($style)'

