#!/usr/bin/env bash

# this is a cript that uses ffmpeg thumbnailer. make sure that package is intalled and also put this file in .local/bin so it is on your path. this file is called by previewer for videos, so if its not on your path it won't work

if ! [ -f "$1" ]; then
	exit 1
fi

cache="$HOME/.cache/vidthumb"
index="$cache/index.json"
movie="$(realpath "$1")"

mkdir -p "$cache"

if [ -f "$index" ]; then
	thumbnail="$(jq -r ". \"$movie\"" <"$index")"
	if [[ "$thumbnail" != "null" ]]; then
		if [[ ! -f "$cache/$thumbnail" ]]; then
			exit 1
		fi
		echo "$cache/$thumbnail"
		exit 0
	fi
fi

thumbnail="$(uuidgen).jpg"

if ! ffmpegthumbnailer -i "$movie" -o "$cache/$thumbnail" -s 0 2>/dev/null; then
	exit 1
fi

if [[ ! -f "$index" ]]; then
	echo "{\"$movie\": \"$thumbnail\"}" >"$index"
fi
json="$(jq -r --arg "$movie" "$thumbnail" ". + {\"$movie\": \"$thumbnail\"}" <"$index")"
echo "$json" >"$index"

echo "$cache/$thumbnail"
